### ISSUE TITLE
Quickstart fails, `valid config/config.yaml is required`

### ISSUE THREAD

**Issue by mattdsteele** [gabek/owncast#52]
Ran through the Dockerized setup in the quickstart, and I was able to successfully build the container, but starting it I'm encountering this error:

```
root@ubuntu-s-1vcpu-1gb-sfo2-01:~/owncast# docker run -p 8080:8080 -p 1935:1935 -it owncast
INFO[2020-07-12T19:20:21Z] Owncast v0.0.0-localdev (unknown)
FATA[2020-07-12T19:20:21Z] ERROR: valid config/config.yaml is required.  Copy config-example.yaml to config.yaml and edit
```

I copied the sample config into `config/config.yaml` before building the container:

```
root@ubuntu-s-1vcpu-1gb-sfo2-01:~/owncast# ls -l config
total 16
-rw-r--r-- 1 root root 4941 Jul 12 19:10 config.go
-rw-r--r-- 1 root root 1441 Jul 12 19:18 config.yaml
-rw-r--r-- 1 root root  842 Jul 12 19:10 configUtils.go
```

The only line I changed was updating `streamingKey` to a different value. I also tried copying `config-example.yaml` directly, and that also failed.

I'll try the non-Docker approach next, but would definitely like to have this running in a container as an option!

For context, this is a stock DigitalOcean VPS running Ubuntu 20.04

**Comment by mattdsteele** [comment]
Another note: while building the project it failed as my machine didn't have `gcc`:

```
...snip
go: downloading github.com/jackpal/go-nat-pmp v1.0.2
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/jmespath/go-jmespath v0.3.0
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exec: "gcc": executable file not found in $PATH
```

Probably worth mentioning that dependency in the quickstart

**Comment by mattdsteele** [comment]
After building from source and running, I'm getting the same error as when running Dockerized:

```
root@ubuntu-s-1vcpu-1gb-sfo2-01:~/owncast# go run main.go
INFO[2020-07-12T19:40:54Z] Owncast v0.0.0-localdev (unknown)
FATA[2020-07-12T19:40:54Z] ERROR: valid config/config.yaml is required.  Copy config-example.yaml to config.yaml and edit
exit status 1
```

Which makes me think the issue is in my config file; I'm just not sure what's causing it.

<details>
<summary>The full file I'm testing in `config/config.yaml`:</summary>
root@ubuntu-s-1vcpu-1gb-sfo2-01:~/owncast# cat config/config.yaml

```
publicHLSPath: webroot/hls
privateHLSPath: hls
ffmpegPath: /usr/bin/ffmpeg
webServerPort: 8080

instanceDetails:
  name: Owncast
  title: Owncast Demo Server
  summary: "This is brief summary of whom you are or what your stream is. You can read more about it at owncast.online.  You can edit this description in your config file."
  extraUserInfoFileName: "/static/content.md"

  logo:
    small: /img/logo128.png
    large: /img/logo128.png

  tags:
    - music
    - software
    - animal crossing

  # See documentation for full list of supported social links.  All optional.
  socialHandles:
    - platform: twitter
      url: http://twitter.com/owncast
    - platform: instagram
      url: http://instagram.biz/owncast
    - platform: facebook
      url: http://facebook.gov/owncast
    - platform: tiktok
      url: http://tiktok.cn/owncast
    - platform: soundcloud
      url: http://soundcloud.com/owncast

videoSettings:
  chunkLengthInSeconds: 4
  streamingKey: abc123
  offlineContent: static/offline.m4v # Is displayed when a stream ends

  streamQualities:
    # Transcode the video to a lower bitrate and resize
    - medium:
    videoBitrate: 800
    encoderPreset: superfast

files:
  maxNumberInPlaylist: 30

ipfs:
  enabled: false
  gateway: https://ipfs.io

s3:
  enabled: false
  endpoint: https://s3.us-west-2.amazonaws.com
  accessKey: ABC12342069
  secret: lolomgqwtf49583949
  region: us-west-2
  bucket: myvideo
```
</details>

**Comment by gabek** [comment]
You're the first to use the Dockerized setup for anything 🥇 

I'll have to update the documentation and code, we recently changed the config to just be in the root of the project instead of `config/config.yaml`, sorry about that!  Hopefully just moving your config there should be good to go.  Let me know!

**Comment by mattdsteele** [comment]
Success!

![image](https://user-images.githubusercontent.com/389077/87255873-2711db00-c454-11ea-812e-dd73103fbf7f.png)

I'll close this out and maybe submit a few PRs for what I mentioned above. We can then use this ticket for any other questions I run into. Thanks!

**Comment by mattdsteele** [comment]
General question as I'm provisioning hardware; about how much disk is required to serve locally? I'd prefer not to have to use cloud storage just to keep things simple, and I've got Cloudflare in front so bandwidth isn't as much of an issue.

Say I set two stream qualities, with bitrates at `1200` and `600`. Out of the box my VPS has 17GB available; is that enough for a few hours of streaming?

Also, do the files in `hls/` get purged automatically? I was looking at some from yesterday, but check again and they were gone 😮

**Comment by mattdsteele** [comment]
From Cloudflare's perspective, I believe the only files I need to exclude from the CDN and disable caching are `/hls/**/*.m3u8`?

**Comment by gabek** [comment]
So the idea is to keep files around only as long as they're useful to be there.  They get cleaned up during two different times:

1. When the service starts up it heavy handedly wipes the working directories of hls files since there's no reference to those files in any playlists anymore, so it just gets rid of them.
2. When a single segment of video drops off a playlist because it's too far in the past, and is no longer referenced in the stream, the file gets removed from the local filesystem.

Because of this the number of files actually on disk at any given time is quite low.  The downside is if you're looking to have a complete back buffer of video and not just focusing on live.  You can adjust the number of segments that are "in play" by changing `maxNumberInPlaylist` in the config file https://github.com/gabek/owncast/blob/master/doc/config-example-full.yaml#L66.   In theory you could crank that up and allow your viewers to seek backwards to have `maxNumberInPlaylist * chunkLengthInSeconds` seconds of video referenceable and seekable, but that really hasn't been something we've tested since we've been focusing on the live edge and keeping the resource footprint low.

As for the cache, that should be correct.  The correct "do not cache" cache-control headers are also set on m3u8 files so hopefully the CDN is respecting those, as well.

I'd love to hear your experience embedding the video into another page, since it's not something we've done.  I'd like to take your implementation tips and throw it in a document to use as a guide for other people.  The catch is having a player that supports HLS.  Our web UI uses [VideoJS](https://videojs.com/) but [hls.js](https://github.com/video-dev/hls.js/) is an option too.

**Comment by mattdsteele** [comment]
Got it! I presume since I'm running in Docker it'll also get wiped when I rebuild the container. I'll probably pull that off into a volume just so it persists.

I'll be focused on live for this use case as well; after my event we may host an edited replay on the site, but that'll probably require some additional tweaks anyhow.

So far embedding has worked great! I'm using hls.js with their quickstart instructions, without any issues. Main gotcha was using native HLS on mobile Safari, [which I should have caught](https://github.com/video-dev/hls.js#compatibility). I'll write something up as I learn more.

**Comment by mattdsteele** [comment]
Just making a note; while testing streaming today I noticed Cloudflare was recording essentially 0% cache hits; nearly all requests for data files were being sent to the owncast instance.

Cloudflare's got a good post [describing the problem with caching live video](https://blog.cloudflare.com/introducing-concurrent-streaming-acceleration/), as well as a solution they provide, but only for their paid Stream Delivery product.

Not sure what to do with this other than maybe note the limitations with CDNing live video in the README? I'll probably end up using S3 or the like, after making sure the egress charges are advantageous...

**Comment by gabek** [comment]
Thanks for the update!  That article is a good reference.

Like any other caching scenario, there has to be enough demand to make it effective, so I'm not surprised.  Not to mention the variability of if a previously cached file in a region A edge server is available yet in a region B edge server.  You could try something like Cloudfront to have a little more control over things, but I'm not sure it would be much better without sufficiant demand.

Depending on what you think the demand for your stream will be it might be completely fine to let your instance be the origin for the video segments, but object storage does allow for some peace of mind.

**Comment by graywolf336** [comment]
I would be curious to see if KeyCDN works well. I've thought about trying this myself, but have yet to do it. https://www.keycdn.com/blog/hls-streaming

**Comment by mattdsteele** [comment]
@graywolf336 I setup KeyCDN and it seems to work OK, though I haven't found a good way to load test to see cache hits.

My naive approach has been to connect up a few browsers and watch the bandwidth charts on my VPS. Any better approaches? I've seen one post using JMeter but want to see if there's any better tooling... https://www.ubik-ingenierie.com/blog/easy-and-realistic-load-testing-of-http-live-streaming-hls-with-apache-jmeter/

**Comment by mattdsteele** [comment]
One other note: I fetched the latest changes and attempted to rebuild the Docker container, and at least on my $5 DigitalOcean VPS it's now unable to build the container:

```
//snip
go: downloading github.com/huin/goupnp v1.0.0
go: downloading github.com/jackpal/go-nat-pmp v1.0.2
go: downloading github.com/cheekybits/genny v1.0.0
go: downloading github.com/francoispqt/gojay v1.2.13
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/marten-seemann/qtls v0.9.1
go: downloading github.com/jmespath/go-jmespath v0.3.0
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
The command '/bin/sh -c CGO_ENABLED=1 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o owncast .' returned a non-zero code: 1
```

I'm using it outside a container and it builds fine; so no worries. But probably worth noting if anyone else tries to build the container on a 1GB instance.

**Comment by gabek** [comment]
Very odd, I'm not seeing any issues building it locally, and I added a Github action now that builds the image and binary to try to catch any issues like this, and that seems to be working ok.  So resources makes sense, but it doesn't make sense that you can't build it, but you can run it.

Thanks for letting me know!  I'll look into it and see what can be done.  I'm assuming it has to do with the requirement of cgo now, but that shouldn't be the end of the world.

**Comment by mattdsteele** [comment]
Did some testing on my instance tonight; we watched a movie over it with a few folks (stats show it maxed at 5 viewers), all in the same city. Unfortunately it doesn't look like KeyCDN did a great job limiting the requests to the origin server:

![image](https://user-images.githubusercontent.com/389077/88471669-6bc85800-ced1-11ea-8e0d-849e454e2b39.png)

I pretty quickly saw a maxing out of bandwidth, and the feed got choppy for everyone:

![image](https://user-images.githubusercontent.com/389077/88471861-61a75900-ced3-11ea-8fdc-3d43e9bd159e.png)

I reconfigured down to a single low-quality stream for the rest of the movie and it got through, but I'm wondering if I just happened to hit the limit for what local serving can support on my little VPS.

So I'm thinking I'll be trying the S3 approach next. DigitalOcean has an [S3-compatible storage offering](https://www.digitalocean.com/products/spaces/), so I'll give that a whirl and let you know how it goes.

Kind of a bummer that KeyCDN didn't do what it says on the tin, but I think switching storage providers will be easier than trying to debug the CDN 🤷

**Comment by gabek** [comment]
I think the S3 approach is the way to go, it's less of a wildcard.  You know for sure the files will be served from there.

I haven't tried the DigitalOcean object storage offering, so I'd love to hear how it works for you.  I wrote some documentation on other providers if it's at all helpful: https://github.com/gabek/owncast/blob/master/doc/S3.md

The recommendation I can make is to find out how to expire files so you don't have a bunch of old segments sitting around taking up space.

**Comment by mattdsteele** [comment]
@gabek This isn't directly an Owncast question, but I noticed in [this post](https://github.com/gabek/owncast/issues/33#issue-646534825) you've used video passthrough for one of the streams.

What broadcaster and settings did you use for that? I've never been able to get a browser to connect with that stream. I'm using vanilla OBS and have tried both hardware (QSV) and software (x264) encoding.

Owncast settings:

```yaml
    - full:
      videoPassthrough: true
      audioPassthrough: true
```
